name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/chekcout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Vertify dependencies
        run: |
          go mod vertify

      - name: Build
        run: go build -v ./...

      - name: Static analysis
        run: |
          go vet ./...
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Test
        run: |
          go test -race -vet=off ./...
